language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip bdist_wheel 

script:
  - pip install -e .
  - pytest test.py

notifications:
  email: false