matrix:
  include: 
    - language: python
      python: 2.7

    - language: python
      python: 3.5

    - language: python
      python: 3.6

install:
  - curl curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
  - export PATH="$HOME/.cargo/bin:$PATH"
  - rustc -V
  - pip install -r requirements.txt

script:
  
  - pip install .
  - pytest test.py

notifications:
  email: false